### ISSUE TITLE
Simple Unity Demo-core is attempting to create a new EventDelegator that overlaps with an existing EventDelegator

### ISSUE THREAD

**Issue by nikitaessen** [WalletConnect/WalletConnectUnity#88]
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/19946297/367d4d6a-6be4-4517-bbf8-84c711ec2da1)

```
ArgumentException: The module Simple Unity Demo-core with context Simple Unity Demo-core is attempting to create a new EventDelegator that overlaps with an existing EventDelegator
WalletConnectSharp.Events.EventDelegator..ctor (WalletConnectSharp.Common.IModule parent) (at <fd565989f95d4292a00cdcbec18984dc>:0)
WalletConnectSharp.Core.WalletConnectCore..ctor (WalletConnectSharp.Core.Models.CoreOptions options) (at <c4da0a682e5a4c5b9f169133159f2f79>:0)
WalletConnect.WalletConnectUnity.InitCore () (at Assets/Packages/WalletConnectUnity/Assets/WalletConnectUnity/Scripts/WalletConnectUnity/WalletConnectUnity.cs:73)
WalletConnect.WCSignClient.InitSignClient () (at Assets/Packages/WalletConnectUnity/Assets/WalletConnectUnity/Scripts/WalletConnectUnity/WCSignClient.cs:74)
WalletConnect.WCSignClient.Awake () (at Assets/Packages/WalletConnectUnity/Assets/WalletConnectUnity/Scripts/WalletConnectUnity/WCSignClient.cs:55)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <88d854ea2c91426ebc464f01cd71aa85>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <88d854ea2c91426ebc464f01cd71aa85>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <88d854ea2c91426ebc464f01cd71aa85>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
BugsnagUnity.BugsnagLogHandler:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

```
This exception happens after lauching the Demo second time, first run is fine. Same exeption happens in Dapp scene I created myself.

**Comment by gigajuwels** [comment]
hi @nikitaessen this issue should be fixed now, as the simple dapp demo is fully working on desktop and mobile. Can you confirm this issue is resolved? If not, can you provide some details on how you reproduce this and what error you are getting?
Thank you

**Comment by gigajuwels** [comment]
reopen if you are still experiencing this issue.

**Comment by charlesteets** [comment]
I've been getting this too, inconsistently unfortunately so it's hard to provide repro steps :\ @nikitaessen  did you happen to learn anything more about the cause of this?

**Comment by charlesteets** [comment]
Created a new issue because this issue persists for me https://github.com/WalletConnect/WalletConnectUnity/issues/114
